FROM python:3.13-slim

WORKDIR /app

COPY requirements-tests.txt /app/

RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements-tests.txt && pip install --no-cache-dir mypy isort black flake8 pylint coverage

VOLUME ["/app", "/app/data"]

CMD ["coverage", "run", "-m", "unittest", "discover", "-s", "app/tests"]