TEST_CONTAINER=fastapi-test
VOLUME=$(PWD):/app:Z

build:
	podman build -f Dockerfile.test -t $(TEST_CONTAINER) .

run:
	podman run -d --name $(TEST_CONTAINER) -v $(VOLUME) $(TEST_CONTAINER)

start:
	podman start $(TEST_CONTAINER)

format: start
	podman exec $(TEST_CONTAINER) isort --check-only .
	podman exec $(TEST_CONTAINER) black --check .

lint: start
	podman exec $(TEST_CONTAINER) pylint app/
	podman exec $(TEST_CONTAINER) flake8 app/

typecheck: start
	podman exec $(TEST_CONTAINER) mypy app/

test: start
	podman exec $(TEST_CONTAINER) \
		coverage run --data-file=/app/.coverage -m unittest discover -s app/tests/
	podman exec $(TEST_CONTAINER) \
		coverage report --data-file=/app/.coverage -m
stop:
	podman stop $(TEST_CONTAINER)
	podman rm $(TEST_CONTAINER)
